xcopy /s /e "%appdata%\LeagueSharp\Repositories\1BA0420E\trunk\Evade\*" "Evade\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\AE72DDF8\trunk\Tracker\*" "Tracker\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\B029831F\trunk\Oracle (Activator)\*" "Oracle (Activator)\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\9AB94A3D\trunk\LeaguesharpStreamingMode\*" "LeaguesharpStreamingMode\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\783119BA\trunk\daYMANs Sidebar\*" "daYMANs Sidebar\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\E0D6961C\trunk\Anti_Camper\*" "Anti_Camper\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\F2E4A9AF\trunk\UniversalMinimapHack\*" "UniversalMinimapHack\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\5129B1DE\trunk\Support\*" "Support\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\EF954DC8\trunk\Shared Experience\*" "Shared Experience\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\E9FE08CC\trunk\MetaSmite\*" "MetaSmite\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\E9FE08CC\trunk\Skin Changer\Skin Changer\*" "Skin Changer\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\BF40B76C\trunk\*" "SAwareness\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\CFB1B437\trunk\xSaliceReligionAIO\xSaliceReligionAIO\*" "xSaliceReligionAIO\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\348C8682\trunk\LexxersAIOCarry\*" "LexxersAIOCarry\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\35EBEEA9\trunk\Marksman\*" "Marksman\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\6A0B8E96\trunk\UnderratedAIO\UnderratedAIO\*" "UnderratedAIO\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\6155DE2\trunk\SigmaSeries\*" "SigmaSeries\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\4F5C1D08\trunk\Stack Overflow\*" "Stack Overflow\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\5EBAAC53\trunk\MAC\*" "MAC\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\FDE57C9F\trunk\Mid or Feed\*" "Mid or Feed\*"

xcopy /s /e "%appdata%\LeagueSharp\Repositories\A218EBE5\trunk\Aatrox\*" "Aatrox\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\B3010427\trunk\DevAnnie\*" "DevAnnie\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\B029831F\trunk\KurisuBlitz\*" "KurisuBlitz\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\E9B3E519\trunk\DatBrand\*" "DatBrand\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\92E8AF66\trunk\Caitlyn\Caitlyn\*" "Caitlyn\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\B3010427\trunk\DevCassio\*" "DevCassio\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\548EFC24\trunk\DSeries\D-Diana\*" "D-Diana\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\D0ED58CE\trunk\FedDrMundo\*" "FedDrMundo\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\212EF0DE\trunk\DZDravenReloaded\DZDraven Reloaded\*" "DZDravenReloaded\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\454C8E6E\trunk\SephElise\*" "SephElise\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\99A82CB1\trunk\PerplexedEzreal\PerplexedEzreal\*" "PerplexedEzreal\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\37804AEF\trunk\SwagPlank\*" "SwagPlank\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\109563C4\trunk\LeagueSharp\GarenOP\*" "GarenOP\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\9D4CA12F\trunk\Gnar\*" "Gnar\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\A4F3B80E\trunk\Gragas\GragasTheDrunkCarry\*" "GragasTheDrunkCarry\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\84EC067B\trunk\SSJ4 Heimerdinger\*" "SSJ4 Heimerdinger\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\FDE57C9F\trunk\Irelia Reloaded\*" "Irelia Reloaded\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\9FDAC0AE\trunk\StonedJarvan\*" "StonedJarvan\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\548EFC24\trunk\JaxQx\*" "JaxQx\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\9305AF66\trunk\Jinx\*" "Jinx\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\9D4CA12F\trunk\Kalista\*" "Kalista\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\1BA0420E\trunk\Karma\*" "Karma\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\1F41B64\trunk\BlackKassadin\*" "BlackKassadin\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\20DEF12F\trunk\Kayle\*" "Kayle\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\AE8D8CD9\trunk\Daimao Kennen\Kennen\*" "Daimao Kennen\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\454C8E6E\trunk\SephKhazix\*" "SephKhazix\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\FF5A0427\trunk\DevKogMaw\*" "DevKogMaw\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\27ABDE44\trunk\LeBlanc 2\LeBlanc 2\*" "LeBlanc 2\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\B7D7F7D2\trunk\FuckingAwesomeLeeSin\FuckingAwesomeLeeSin\*" "FuckingAwesomeLeeSin\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\CFB1B437\trunk\LissandraLetitGoLetItGOOOOO\LissandraLetitGoLetItGOOOOO\*" "LissandraLetitGoLetItGOOOOO\*"
pause