xcopy /s /e "%appdata%\LeagueSharp\Repositories\1BA0420E\trunk\Evade\*" "Evade\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\AE72DDF8\trunk\Tracker\*" "Tracker\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\B029831F\trunk\Oracle (Activator)\*" "Oracle (Activator)\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\9AB94A3D\trunk\LeaguesharpStreamingMode\*" "LeaguesharpStreamingMode\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\783119BA\trunk\daYMANs Sidebar\*" "daYMANs Sidebar\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\E0D6961C\trunk\Anti_Camper\*" "Anti_Camper\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\F2E4A9AF\trunk\UniversalMinimapHack\*" "UniversalMinimapHack\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\683DA673\trunk\LeBlanc\*" "LeBlanc\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\1BA0420E\trunk\Syndra\*" "Syndra\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\1BA0420E\trunk\Ziggs\*" "Ziggs\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\5129B1DE\trunk\Support\*" "Support\*"
xcopy /s /e "%appdata%\LeagueSharp\Repositories\92E8AF66\trunk\Jinx\*" "Jinx\*"
pause